### ISSUE TITLE
性能相比官方版本有很大差距

### ISSUE THREAD

**Issue by norris-young** [Berrysoft/msys-git-for-windows#10]
大佬 你好~
我主要是想用ucrt64的版本，但是官方没有。所以尝试你这里发布的版本，但是遇到了一个性能问题。

在同一个 [dotemacs ](https://github.com/norris-young/dotemacs) repo下`git status`（有很多submodule)
用git-for-windows的官方发布版本（编译好的bin，msys2 pacman安装）耗时`1.656s`(通过time获得）
用这里发布的版本（编译好的bin，msys2 pacman安装）耗时`11.521s`(通过time获得）

我有两台windows环境，一台最近重新装了一次（也是预编译版本），性能变好了，和官方发布版本持平。
另一台我也尝试重装了一次，但是性能依然很差。

我装过你这里的ucrt64/mingw64版本，也尝试过自己编译，性能都不好（除了最近在一台环境重装的预编译版本）。
我自己判断应该不是c库变化引起的。
不知道问题出在哪里，能不能指导指导，有啥分析思路吗？
尝试过GIT_TRACE对比，但是基本上就是所有的操作都慢了一些，最后就差了很多。

**Comment by norris-young** [comment]
似乎和env的改动有关系 去掉以后速度好很多~ 我先close了

**Comment by Berrysoft** [comment]
你指的是 env 相关的 patch 吗？有趣。如果你遇到了性能问题可以先去掉，我用它是因为遇到了一些不太容易解决的 shebang 问题

**Comment by Berrysoft** [comment]
我试了一下，env 确实在其中有点影响，不过第一次运行 git status 和后面再运行耗时也是不同的，可以考虑多次运行测试看看。

**Comment by Berrysoft** [comment]
我更新了 patch，在 exe subcommand 中这个 patch 应当不再影响性能。你所说的这个仓库的 git status 的性能也提升了
